<?php

/**
 * LoginForm class.
 * LoginForm is the data structure for keeping
 * user login form data. It is used by the 'login' action of 'SiteController'.
 */
class ReferalViewForm extends CFormModel
{
  public $begin;
  public $end;

  public $beginTS;
  public $endTS;


  public function init() {
	  parent::init(); // TODO: Change the autogenerated stub

	  $this->attributes = $_POST['ReferalViewForm'];

	  if (!$this->begin) {
	  	$this->begin = date('d/m/Y', strtotime('-1 month'));
	  }
	  if (!$this->end) {
	  	$this->end = date('d/m/Y');
	  }

	  $this->beginTS = Yii::app()->dateFormatter->format("d.M.y", CDateTimeParser::parse($this->begin, 'dd/MM/yyyy'));
      $this->beginTS = strtotime($this->beginTS);

	  $this->endTS = Yii::app()->dateFormatter->format("d.M.y", CDateTimeParser::parse($this->end, 'dd/MM/yyyy'));
      $this->endTS = strtotime($this->endTS);
  }

	/**
   * Declares the validation rules.
   * The rules state that username and password are required,
   * and password needs to be authenticated.
   */
  public function rules()
  {
    return array(
    	array('begin, end', 'safe')
    );
  }

  /**
   * Declares attribute labels.
   */
  public function attributeLabels()
  {
    return array(
        'begin' => 'Начало периода',
        'end'   => 'Конец периода',
    );
  }
}
