<?php

/**
 * This is the model class for table "{{pw_costs_content}}".
 *
 * The followings are the available columns in table '{{pw_costs_content}}':
 * @property integer $id
 * @property integer $box_id
 * @property string $name
 * @property integer $chance
 *
 * @property PwCostsContentItems[] $items
 * @property PwCostsBox[] $box
 */
class PwCostsContent extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{pw_costs_content}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('box_id, name', 'required'),
			array('box_id, chance', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, box_id, name, chance', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'items' => array(self::HAS_MANY, 'PwCostsContentItems', 'content_id'),
			'box' => array(self::HAS_ONE, 'PwCostsBox', array('id' => 'cost_id')),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'box_id' => 'ID ящика',
			'name' => 'Название варианта',
			'chance' => 'Шанс выпадания',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('box_id',$this->box_id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('chance',$this->chance);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return PwCostsContent the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function beforeDelete() {
		foreach ($this->items as $one) $one->delete();
		return parent::beforeDelete(); // TODO: Change the autogenerated stub
	}

}
